import baseAssert from 'node:assert/strict';
let checks=0;
const assert=new Proxy(baseAssert,{get(target,key){const value=target[key];return typeof value==='function'? (...args)=>{checks++;return value(...args);}:value;}});
import fs from 'node:fs';
import {research,grade,sensitivity,validateImport,scenario,compareReports} from '../dist/engine.mjs';
const data=JSON.parse(fs.readFileSync(new URL('../data/research.json',import.meta.url)));
const report=await research(data);
assert.equal(report.companies.length,6);
assert.deepEqual(report.evidence_graph.map(r=>r.evidence_level),['A','B','B','B','B','B','C']);
assert.equal(report.comparisons.length,2);
assert.equal(report.evidence_graph[0].financial.revenue_share,null);
assert.equal((await research(data,'固态电池','2023-01-01')).comparisons.length,0);
assert.ok((await research(data,'固态电池','2023-01-01')).evidence_graph.every(r=>r.evidence_level==='M'));
await assert.rejects(()=>research(data,'算力网络'));
await assert.rejects(()=>research(data,'固态电池目标价'));
await assert.rejects(()=>research(data,'固态电池','2025-02-30'));
assert.equal(sensitivity(-.2,.3,.7),1.8);
assert.equal(sensitivity(-.2,.3,1),0);
assert.throws(()=>sensitivity(-.2,2,.7));
assert.equal(scenario(data,report,'lithium_down').paths.length,3);
assert.throws(()=>scenario(data,report,'unknown'));
const evidence=structuredClone(data.evidence);evidence[0].summary+='虚构';
assert.equal((await grade(data.relations[0],evidence,'2025-03-01')).evidence_level,'M');
const template={company_id:'qs',node_id:'cell',route:'solid_separator',title:'测试夹具',url:data.evidence[2].url,published_at:'2024-07-11',kind:'research',summary:'仅用于校验待审流程的测试材料摘要。',locator:'Test',source_type:'official_material'};
assert.equal((await validateImport(template,data)).review_status,'unreviewed');
await assert.rejects(()=>validateImport({...template,review_status:'reviewed'},data));
await assert.rejects(()=>validateImport({...template,url:'http://127.0.0.1'},data));
for(const [route,ids] of [['all_solid',['sldp']],['solid_separator',['qs']]]){
 const r=await research(data,'固态电池','2025-03-01',route);
 const path=scenario(data,r,'delay').paths.find(p=>p.node_id==='process');
 assert.deepEqual(path.company_ids,ids);
 assert.equal(path.evidence_ids.length,1);
}
const updated=structuredClone(data),extra=structuredClone(updated.evidence[2]);extra.id='test-added-evidence';extra.title='仅用于测试的同级证据';
updated.evidence.push(extra);updated.relations.find(r=>r.company_id==='qs').evidence_ids.push(extra.id);
const next=await research(updated),diff=compareReports(report,next),change=diff.changes.find(c=>c.company_id==='qs');
assert.equal(change.grade_changed,false);
assert.equal(change.level,'B');
assert.equal(change.added_evidence[0].id,'test-added-evidence');
assert.equal(diff.filters_changed,false);
assert.equal(compareReports(report,report).changes.length,0);
const money=structuredClone(data);money.evidence[0].revenue_amount=12000000;
assert.equal(compareReports(report,await research(money)).changes[0].financial_changes[0].field,'revenue_amount');
assert.equal(compareReports(report,await research(data,'固态电池','2023-01-01')).filters_changed,true);
const sample=JSON.parse(fs.readFileSync(new URL('../data/update-sample.json',import.meta.url)));
const candidate=await validateImport(sample,data),updatedReal=structuredClone(data);
updatedReal.evidence.push(candidate);updatedReal.relations.find(r=>r.company_id==='qs').evidence_ids.push(candidate.id);
const qsOf=r=>r.evidence_graph.find(e=>e.company_id==='qs');
assert.equal(qsOf(await research(updatedReal,'固态电池','2026-02-25')).citation_source.length,1);
candidate.review_status='reviewed';
assert.equal(qsOf(await research(updatedReal)).citation_source.length,1);
const realNext=await research(updatedReal,'固态电池','2026-02-25');
assert.equal(qsOf(realNext).evidence_level,'B');
assert.equal(qsOf(realNext).financial,null);
assert.equal(compareReports(report,realNext).changes.find(c=>c.company_id==='qs').added_evidence[0].title,sample.title);
console.log('Browser reference engine: '+checks+' assertions passed.');
