"""Encode actual browser captures at their original timestamps, with captions.

Raw captures are kept in the task work directory, outside the source package.
No browser actions or simulated interface frames are generated by this script.
"""
import argparse
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import imageio_ffmpeg

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--captures', type=Path, required=True)
args = parser.parse_args()
manifest_path = args.captures / 'manifest.json'
m = json.loads(manifest_path.read_text())
assert not m['error'] and 60 <= m['duration'] <= 180
frames = m['frames']
assert len(frames) > 60
concat = []
for i, frame in enumerate(frames):
    path = (args.captures / frame['file']).resolve()
    assert path.exists()
    next_time = frames[i+1]['time'] if i+1 < len(frames) else m['duration']
    concat += [f"file '{path}'", f"duration {max(.01, next_time-frame['time']):.6f}"]
concat += [f"file '{(args.captures / frames[-1]['file']).resolve()}'"]
sequence = args.captures / 'sequence.txt'
sequence.write_text('\n'.join(concat)+'\n')
def ass_time(t):
    return f'{int(t)//3600}:{int(t)//60%60:02}:{t%60:05.2f}'
def srt_time(t):
    ms=round(t*1000)
    return f'{ms//3600000:02}:{ms//60000%60:02}:{ms//1000%60:02},{ms%1000:03}'
events, subtitles = [], []
for i, stage in enumerate(m['stages']):
    end=m['stages'][i+1]['start'] if i+1<len(m['stages']) else m['duration']
    caption=stage['caption']
    events.append(f"Dialogue: 0,{ass_time(stage['start'])},{ass_time(end)},Default,,0,0,0,,{caption}")
    subtitles.append(f"{i+1}\n{srt_time(stage['start'])} --> {srt_time(end)}\n{caption}\n")
ass = args.captures / 'live.ass'
ass.write_text('[Script Info]\nPlayResX: 1280\nPlayResY: 820\nWrapStyle: 0\n[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\nStyle: Default,Heiti SC,21,&H00FFFFFF,&H00FFFFFF,&H00101B2C,&H00101B2C,0,0,0,0,100,100,0,0,1,0,0,2,30,30,22,1\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n'+'\n'.join(events)+'\n')
output = ROOT/'docs/ChainScope_Task1_live_demo.mp4'
subprocess.run([imageio_ffmpeg.get_ffmpeg_exe(),'-hide_banner','-loglevel','error','-y','-f','concat','-safe','0','-i',str(sequence),'-vf',f"scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:820:(ow-iw)/2:0:color=0x101b2c,ass='{ass}':fontsdir='/System/Library/Fonts',fps=24",'-t',str(m['duration']),'-c:v','libx264','-crf','24','-preset','fast','-pix_fmt','yuv420p','-movflags','+faststart',str(output)],check=True)
shutil.copy2(output,ROOT/'dist'/output.name)
(ROOT/'docs/live_demo_zh.srt').write_text('\n'.join(subtitles))
proof={k:m[k] for k in ['recorded_at','mode','duration','stages','error']}
proof.update(frame_count=len(frames),capture_manifest_sha256=hashlib.sha256(manifest_path.read_bytes()).hexdigest(),video_sha256=hashlib.sha256(output.read_bytes()).hexdigest(),file_size_bytes=output.stat().st_size)
(ROOT/'docs/live_demo_capture.json').write_text(json.dumps(proof,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'duration':m['duration'],'frames':len(frames),'bytes':output.stat().st_size}))
